In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [3]:
orders.shape

(99441, 8)

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [5]:
orders["order_status"]

0        delivered
1        delivered
2        delivered
3        delivered
4        delivered
           ...
99436    delivered
99437    delivered
99438    delivered
99439    delivered
99440    delivered
Name: order_status, Length: 99441, dtype: str

In [6]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 13.0 MB

In [7]:
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"] - orders["order_estimated_delivery_date"]
).dt.days

orders[
    [
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_delay_days",
    ]
].head(10)

,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days
0,2017-10-10 21:25:13,2017-10-18,-8.0
1,2018-08-07 15:27:45,2018-08-13,-6.0
2,2018-08-17 18:06:29,2018-09-04,-18.0
3,2017-12-02 00:28:42,2017-12-15,-13.0
4,2018-02-16 18:17:02,2018-02-26,-10.0
5,2017-07-26 10:57:55,2017-08-01,-6.0
6,NaT,2017-05-09,NaN
7,2017-05-26 12:55:51,2017-06-07,-12.0
8,2017-02-02 14:08:10,2017-03-06,-32.0
9,2017-08-16 17:14:30,2017-08-23,-7.0

In [8]:
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
orders_items = orders.merge(order_items, on="order_id", how="left")

print("orders shape:", orders.shape)
print("order_items shape:", order_items.shape)
print("merged shape:", orders_items.shape)

orders_items.head()

orders shape: (99441, 9)
order_items shape: (112650, 7)
merged shape: (113425, 15)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [10]:
orders_items = orders.merge(order_items, on="order_id", how="left")

print("orders shape:", orders.shape)
print("order_items shape:", order_items.shape)
print("merged shape:", orders_items.shape)

orders_items.head()

orders shape: (99441, 9)
order_items shape: (112650, 7)
merged shape: (113425, 15)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [11]:
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")

print("order_payments shape:", order_payments.shape)
print("order_reviews shape:", order_reviews.shape)

order_payments shape: (103886, 5)
order_reviews shape: (99224, 7)

In [12]:
payments_agg = (
    order_payments.groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_value", "count"),
    )
    .reset_index()
)

print("payments_agg shape:", payments_agg.shape)
payments_agg.head()

payments_agg shape: (99440, 3)

                           order_id  total_payment_value  payment_count
0  00010242fe8c5a6d1ba2dd792cb16214                72.19              1
1  00018f77f2f0320c557190d7a144bdd3               259.83              1
2  000229ec398224ef6ca0657da4fc703e               216.87              1
3  00024acbcdf0a6daa1e931b038114c75                25.78              1
4  00042b26cf59d7ce69dfabb4e55b4fd9               218.04              1

In [13]:
reviews_agg = (
    order_reviews.groupby("order_id")
    .agg(
        avg_review_score=("review_score", "mean"),
        review_count=("review_score", "count"),
    )
    .reset_index()
)

print("reviews_agg shape:", reviews_agg.shape)
reviews_agg.head()

reviews_agg shape: (98673, 3)

                           order_id  avg_review_score  review_count
0  00010242fe8c5a6d1ba2dd792cb16214               5.0             1
1  00018f77f2f0320c557190d7a144bdd3               4.0             1
2  000229ec398224ef6ca0657da4fc703e               5.0             1
3  00024acbcdf0a6daa1e931b038114c75               4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9               5.0             1

In [14]:
full_data = orders_items.merge(payments_agg, on="order_id", how="left")
full_data = full_data.merge(reviews_agg, on="order_id", how="left")

print("orders_items shape:", orders_items.shape)
print("full_data shape:", full_data.shape)

full_data.head()

orders_items shape: (113425, 15)
full_data shape: (113425, 19)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_payment_value,payment_count,avg_review_score,review_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,38.71,3.0,4.0,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,141.46,1.0,4.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,179.12,1.0,5.0,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,72.20,1.0,5.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,28.62,1.0,5.0,1.0

In [15]:
products = pd.read_csv("olist_products_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

products = products.merge(category_translation, on="product_category_name", how="left")

print("products shape:", products.shape)
products[
    ["product_id", "product_category_name", "product_category_name_english"]
].head()

products shape: (32951, 10)

,product_id,product_category_name,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,housewares

In [16]:
full_data = full_data.merge(
    products[["product_id", "product_category_name_english"]],
    on="product_id",
    how="left",
)

print("full_data shape:", full_data.shape)
full_data[["order_id", "product_id", "product_category_name_english"]].head()

full_data shape: (113425, 20)

,order_id,product_id,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,87285b34884572647811a353c7ac498a,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,595fac2a385ac33a80bd5114aec74eb8,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,aa4383b373c6aca5d8797843e5594415,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,d0b61bfb1de832b15ba9d266ca96e5b0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,65266b2da20d04dbe00c5c2d3bb7859e,stationery

In [17]:
full_data.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1968
order_delivered_customer_date    3229
order_estimated_delivery_date       0
delivery_delay_days              3229
order_item_id                     775
product_id                        775
seller_id                         775
shipping_limit_date               775
price                             775
freight_value                     775
total_payment_value                 3
payment_count                       3
avg_review_score                  961
review_count                      961
product_category_name_english    2402
dtype: int64

In [18]:
missing_category = full_data[full_data["product_category_name_english"].isnull()]
print("Rows with missing category:", missing_category.shape[0])
print(
    "Of these, rows with a valid product_id:",
    missing_category["product_id"].notnull().sum(),
)

Rows with missing category: 2402
Of these, rows with a valid product_id: 1627

In [19]:
problem_product_ids = missing_category.loc[
    missing_category["product_id"].notnull(), "product_id"
].unique()

sample_products = products[products["product_id"].isin(problem_product_ids)]
print(
    sample_products[
        ["product_id", "product_category_name", "product_category_name_english"]
    ].head(10)
)
print(
    "\nHow many of these have a blank product_category_name in the original products table:"
)
print(sample_products["product_category_name"].isnull().sum())

                           product_id product_category_name  \
105  a41e356c76fab66334f36de622ecbd3a                   NaN
128  d8dee61c2034d6d075997acef1870e9b                   NaN
145  56139431d72cd51f19eb9f7dae4d1617                   NaN
154  46b48281eb6d663ced748f324108c733                   NaN
197  5fb61f482620cb672f5e586bb132eae9                   NaN
244  e10758160da97891c2fdcbc35f0f031d                   NaN
294  39e3b9b12cd0bf8ee681bbc1c130feb5                   NaN
299  794de06c32a626a5692ff50e4985d36f                   NaN
347  7af3e2da474486a3519b0cba9dea8ad9                   NaN
428  629beb8e7317703dcc5f35b5463fd20e                   NaN

    product_category_name_english
105                           NaN
128                           NaN
145                           NaN
154                           NaN
197                           NaN
244                           NaN
294                           NaN
299                           NaN
347                           NaN
428                           NaN

How many of these have a blank product_category_name in the original products table:
610

In [20]:
category_fix = {
    "pc_gamer": "pc_gamer",
    "portateis_cozinha_e_preparadores_de_alimentos": "kitchen_portables_and_food_preparers",
}

full_data["product_category_name_english"] = full_data[
    "product_category_name_english"
].fillna(full_data["product_category_name"].map(category_fix))

full_data["product_category_name_english"] = full_data[
    "product_category_name_english"
].fillna("unknown")

print(full_data["product_category_name_english"].isnull().sum())

KeyError: 'product_category_name'

In [21]:
product_to_category = products.set_index("product_id")["product_category_name"]

fallback_category = full_data["product_id"].map(product_to_category).map(category_fix)

full_data["product_category_name_english"] = full_data[
    "product_category_name_english"
].fillna(fallback_category)
full_data["product_category_name_english"] = full_data[
    "product_category_name_english"
].fillna("unknown")

print(full_data["product_category_name_english"].isnull().sum())

0

In [22]:
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")

full_data = full_data.merge(
    customers[["customer_id", "customer_city", "customer_state"]],
    on="customer_id",
    how="left",
)

full_data = full_data.merge(
    sellers[["seller_id", "seller_city", "seller_state"]], on="seller_id", how="left"
)

print("full_data shape:", full_data.shape)
full_data[["customer_id", "customer_state", "seller_id", "seller_state"]].head()

full_data shape: (113425, 24)

,customer_id,customer_state,seller_id,seller_state
0,9ef432eb6251297304e76186b10a928d,SP,3504c0cb71d7fa48d967e0e4c94d59d9,SP
1,b0830fb4747a6c6d20dea0b8c802d7ef,BA,289cdb325fb7e7f891c38608bf9e0962,SP
2,41ce2a54c0b03bf3443c3d931a367089,GO,4869f7a5dfa277a7dca6462dcf3b52b2,SP
3,f88197465ea7920adcdbec7375364d82,RN,66922902710d126a0e7d26b0e3805106,MG
4,8ab97904e6daea8866dbdbc4fb7aad2c,SP,2c9e548be18521d1c43cde1c582c6de8,SP

In [23]:
full_data.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 161
order_delivered_carrier_date     1968
order_delivered_customer_date    3229
order_estimated_delivery_date       0
delivery_delay_days              3229
order_item_id                     775
product_id                        775
seller_id                         775
shipping_limit_date               775
price                             775
freight_value                     775
total_payment_value                 3
payment_count                       3
avg_review_score                  961
review_count                      961
product_category_name_english       0
customer_city                       0
customer_state                      0
seller_city                       775
seller_state                      775
dtype: int64

In [24]:
full_data.to_csv("olist_full_data_cleaned.csv", index=False)
print("Saved! Final shape:", full_data.shape)

Saved! Final shape: (113425, 24)